### ISSUE TITLE
[CRITICAL] - repository out of date! Last commit 2 years ago - latest nuget 3 days ago!!

### ISSUE THREAD

**Issue by gentledepp** [jsmarcus/Xamarin.Plugins#121]
We noticed there is a new Xam.Plugins.Iconize package available on nuget.
However, the repository has been stale for 2 years.

Could you please push your changes?

We would like to fix a nasty NullReferenceException in the UWP Part:

```   

at Plugin.Iconize.IconNavigationPageRenderer.<UpdateToolbarItems>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

```

**Comment by masonyc** [comment]
Iconize got a new project repo at https://github.com/jsmarcus/Iconize

**Comment by gentledepp** [comment]
oh thanks for clarifying that.
I stumbled across the new repository recently.
May be a good idea to add a disclaimer to the readme.md that this repository is abandoned - including a link to the new repository ;-)

Thank you!
